rm(list = ls())
data = read.table("D:\\Study\\2016\\Experiments\\Integration\\Results\\LUSC\\LRAcluster\\new\\consensus input\\mi_me_cnv_3.csv", header=F, sep=",")
data1 = as.matrix(data)
library(ConsensusClusterPlus)
results=ConsensusClusterPlus(data1,maxK = 8,reps=1000,pItem = 0.8,pFeature = 1,clusterAlg = "kmdist",distance="euclidean")
icl=calcICL(results)
icl[["clusterConsensus"]]
write.csv(icl$clusterConsensus,file="D:\\Study\\2016\\Experiments\\Integration\\Results\\LUSC\\LRAcluster\\new\\consensus result//mi_me_cnv_3_clusterConsensus.csv")
write.csv(results[[2]]$consensusClass,file="D:\\Study\\2016\\Experiments\\Integration\\Results\\LUSC\\LRAcluster\\new\\consensus result\\mi_me_cnv_3_2.csv")
write.csv(results[[3]]$consensusClass,file="D:\\Study\\2016\\Experiments\\Integration\\Results\\LUSC\\LRAcluster\\new\\consensus result\\mi_me_cnv_3_3.csv")
write.csv(results[[4]]$consensusClass,file="D:\\Study\\2016\\Experiments\\Integration\\Results\\LUSC\\LRAcluster\\new\\consensus result\\mi_me_cnv_3_4.csv")
write.csv(results[[5]]$consensusClass,file="D:\\Study\\2016\\Experiments\\Integration\\Results\\LUSC\\LRAcluster\\new\\consensus result\\mi_me_cnv_3_5.csv")
write.csv(results[[6]]$consensusClass,file="D:\\Study\\2016\\Experiments\\Integration\\Results\\LUSC\\LRAcluster\\new\\consensus result\\mi_me_cnv_3_6.csv")
write.csv(results[[7]]$consensusClass,file="D:\\Study\\2016\\Experiments\\Integration\\Results\\LUSC\\LRAcluster\\new\\consensus result\\mi_me_cnv_3_7.csv")
write.csv(results[[8]]$consensusClass,file="D:\\Study\\2016\\Experiments\\Integration\\Results\\LUSC\\LRAcluster\\new\\consensus result\\mi_me_cnv_3_8.csv")
# write.csv(results[[9]]$consensusClass,file="D://Study//2016//Experiments//Integration//Results//BRCA//LRAcluster//consensus result//m_mi_me_cnv_9.csv")
# write.csv(results[[10]]$consensusClass,file="D://Study//2016//Experiments//Integration//Results//BRCA//LRAcluster//consensus result//m_mi_me_cnv_10.csv")
# write.csv(results[[11]]$consensusClass,file="D://Study//2016//Experiments//Integration//Results//BRCA//LRAcluster//consensus result//m_mi_me_cnv_11.csv")
# write.csv(results[[12]]$consensusClass,file="D://Study//2016//Experiments//Integration//Results//BRCA//LRAcluster//consensus result//m_mi_me_cnv_12.csv")
# write.csv(results[[13]]$consensusClass,file="D://Study//2016//Experiments//Integration//Results//BRCA//LRAcluster//consensus result//m_mi_me_cnv_13.csv")
# write.csv(results[[14]]$consensusClass,file="D://Study//2016//Experiments//Integration//Results//BRCA//LRAcluster//consensus result//m_mi_me_cnv_14.csv")
# write.csv(results[[15]]$consensusClass,file="D://Study//2016//Experiments//Integration//Results//BRCA//LRAcluster//consensus result//m_mi_me_cnv_15.csv")
print("Done")
